title: Nejedz palmov√Ω olej
baseURL: https://xenodochial-kalam-4dd3db.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

